Create RollUp Smart Contract
bosagora/rollup-server pull request #31
Opened 2022-11-29 09:04 UTC by TrustHenry

The block header addition function and 
the block header inquiry size inquiry function have been added with block height.

추가적으로 여러 블록헤더 추가 테스트를 진행 하겠습니다.

2022-11-30 01:39 UTC, Kang-Simon commented on test/contracts/RollUp.test.ts
> +    });
Height 를 1로 도 한번 넣어서 테스트 해주세요

2022-11-30 01:41 UTC, Kang-Simon approved these changes
LGTM

2022-11-30 02:11 UTC, TrustHenry commented on test/contracts/RollUp.test.ts
> +    });
추가 하였습니다.

2022-11-30 04:37 UTC, MichaelKim20 requested changes
블록저장시 인덱스가 height 이고 값이 블록해드인 Array를 사용해주세요.
블록의 높이가 0부터 1씩 증가되도록한 검증로직으로 코드가 단순하게 될 것 같습니다.

2022-11-30 04:37 UTC, MichaelKim20 commented on contracts/RollUp.sol
> +    }
이전 블록의 해시 뿐만 아니라 현재 블록의 해시도 추가해 주세요

2022-11-30 04:37 UTC, MichaelKim20 commented on contracts/RollUp.sol
> +    }
prevBlock, curBlock 이 어떤지?

2022-11-30 04:37 UTC, MichaelKim20 commented on contracts/RollUp.sol
> +    mapping(uint64 => BlockHeader) internal blockMap;
블록의 높이는 0부터 하나씩 증가되도록 시스템이 구축되었습니다. 아래 코드의 추가로 인하여
require((lastHeight == type(uint64).max && _height == 0) || lastHeight + 1 == _height, "E001");
따라서 굳이 heightArray가 필요 없겠습니다.
그리고 블록높이가 0부터 순차적으로 증가하기 때문에 height 기준의 blockMap은 필요없고, height 기준의 blockArray로 변경하는 것이 좋겠습니다.
BlockHeight[] internal blockArray

2022-11-30 04:37 UTC, MichaelKim20 commented on contracts/RollUp.sol
> +    mapping(uint64 => BlockHeader) internal blockMap;
키가 블록해시이고, 값이 블록높이인 맵을 하나 만든다면, 블록해시로 조회가 가능할 것 같습니다.
mapping(bytes32 => uint64) internal blockMap;

2022-11-30 04:40 UTC, TrustHenry commented on contracts/RollUp.sol
> +    mapping(uint64 => BlockHeader) internal blockMap;
> 따라서 굳이 heightArray가 필요 없겠습니다.
네 맞습니다. 저도 그렇게 생각 했습니다.

2022-11-30 04:42 UTC, TrustHenry commented on contracts/RollUp.sol
> +    mapping(uint64 => BlockHeader) internal blockMap;
> 키가 블록해시이고, 값이 블록높이인 맵을 하나 만든다면, 블록해시로 조회가 가능할 것 같습니다.

네 블록해시 조회시에는 필요 할 것 입니다.

2022-11-30 06:06 UTC, TrustHenry commented on contracts/RollUp.sol
> +    }
적용 되었습니다.

2022-11-30 06:06 UTC, TrustHenry commented on contracts/RollUp.sol
> +    mapping(uint64 => BlockHeader) internal blockMap;
적용 되었습니다.

2022-11-30 06:26 UTC, MichaelKim20 requested changes
솔리디티에 주석을 좀 추가해 주세요

https://docs.soliditylang.org/en/v0.8.16/natspec-format.html

2022-11-30 06:26 UTC, MichaelKim20 commented on contracts/RollUp.sol
> +        uint32 timestamp;
```suggestion
        uint64 timestamp;
```
이렇게 하는것이 어떤가요? 자바스크립트의 number의 최대값은 2^53-1 입니다. 2^32보다는 크네요

2022-11-30 06:26 UTC, MichaelKim20 commented on contracts/RollUp.sol
> +    event addBlock(uint64 _height);
이벤트는 보통 대문자로 표시되는 것 같아요. 그리고 과거형으로 BlockAdded 또는 AddedBlock이 어떤가요?

2022-11-30 06:35 UTC, TrustHenry commented on contracts/RollUp.sol
> +    event addBlock(uint64 _height);
적용 되었습니다.

2022-11-30 06:35 UTC, TrustHenry commented on contracts/RollUp.sol
> +        uint32 timestamp;
적용 되었습니다.

2022-11-30 08:59 UTC, MichaelKim20 requested changes
하나만 확인해 주세요

2022-11-30 08:59 UTC, MichaelKim20 commented on contracts/RollUp.sol
> +        uint64 height = blockMap[_blockHash];
맵의 키 _blockHash에 해당하는 키가 존재하지 않으면 항상 0을 리턴할 것 같아요

2022-12-01 02:04 UTC, TrustHenry commented on contracts/RollUp.sol
> +        uint64 height = blockMap[_blockHash];
네 맞습니다. 해당 로직을 개선 했습니다.

2022-12-01 02:22 UTC, MichaelKim20 approved these changes
LGTM

2022-12-01 02:22 UTC, merged