Create api for transaction recording
bosagora/rollup-server pull request #47
Opened 2022-12-06 06:54 UTC by Kang-Simon

2022-12-07 01:02 UTC, TrustHenry commented on src/service/routers/RollupRouter.ts
> +    private async postTransactionSave(req: express.Request, res: express.Response) {
```suggestion
    private async postTransactionRecord(req: express.Request, res: express.Response) {
```
API 라우터와 연결된 함수명을 쓰는것이 읽기 좋습니다.

2022-12-07 01:03 UTC, TrustHenry commented on src/service/routers/RollupRouter.ts
> +            this.postTransactionSave.bind(this)
```suggestion
            this. postTransactionRecord.bind(this)
```

2022-12-08 02:25 UTC, MichaelKim20 requested changes

2022-12-08 02:25 UTC, MichaelKim20 commented on src/service/routers/RollupRouter.ts
> +            await this.pool.add(DBTransaction.make(tx));
pool에 트랜잭션을 넣기 전에
tx.verify() 를 실행해서 서명을 검증하고 이 값이 false 이면 오류를 리턴하는 코드를 추가해야 해 주세요

2022-12-08 02:25 UTC, MichaelKim20 commented on src/service/routers/RollupRouter.ts
> +
아무나 이 API를 호출할 수 없도록 처리해 주세요
참조) https://github.com/bosagora/remote-wallet/blob/v0.x.x/src/service/routers/WalletRouter.ts#L191-L198

2022-12-08 02:25 UTC, MichaelKim20 commented on test/service/RollupRouter.test.ts
> +                "0x64ca000fe0fbb7ca96274dc836e3b286863b24fc47576748f0945ce3d07f58ed47f2dda151cbc218d05de2d2363cef6444ab628670d2bc9cf7674862e6dc51c81b",
```suggestion
                "0xf3d449722e5e38d0045bdcf538286e44cfc04cde67fa2e7beeca6c3f275b6db723d2cdc4c2cffe1cfa0441f6390975ddeaed6d4bbc5dbd2610e9cae32634f9cc1c",
```

2022-12-08 04:02 UTC, Kang-Simon commented on src/service/routers/RollupRouter.ts
> +
https://github.com/bosagora/rollup-server/issues/50

2022-12-08 07:46 UTC, Kang-Simon commented on src/service/routers/RollupRouter.ts
> +
처리완료

2022-12-08 07:46 UTC, Kang-Simon commented on test/service/RollupRouter.test.ts
> +                "0x64ca000fe0fbb7ca96274dc836e3b286863b24fc47576748f0945ce3d07f58ed47f2dda151cbc218d05de2d2363cef6444ab628670d2bc9cf7674862e6dc51c81b",
처리완료

2022-12-08 07:46 UTC, Kang-Simon commented on src/service/routers/RollupRouter.ts
> +            await this.pool.add(DBTransaction.make(tx));
처리완료

2022-12-09 01:20 UTC, MichaelKim20 approved these changes
LGTM

2022-12-09 01:20 UTC, merged