A schedule for send block header to the blockchain
bosagora/rollup-server pull request #49
Opened 2022-12-08 02:19 UTC by TrustHenry

2022-12-08 03:40 UTC, MichaelKim20 requested changes

2022-12-08 03:40 UTC, MichaelKim20 commented on src/main.ts
> +            schedulers.push(new SendBlock());
별도의 설정을 가지고 있어야 하지 않을 까요?
컨트랙트의 주소, 실행주기(초), 등록하는 계정등이 필요할것 같습니다.

2022-12-08 03:40 UTC, MichaelKim20 commented on src/service/scheduler/SendBlock.ts
> +            const last_height: BigNumber = await this._rollup.connect(this._adminSigner).getLastHeight();
bigint 로 변환해서 하는것이 좋겠습니다. 
이미 BlockHeader에서는 bigint로 정의해 놓았습니다.

2022-12-08 03:40 UTC, MichaelKim20 commented on src/service/scheduler/SendBlock.ts
> +            ) as RollUp;
매번 만들 필요가 있을 까요?
생성자에서 초기화 하면 되지 않을 까요?

2022-12-08 03:40 UTC, MichaelKim20 commented on src/service/scheduler/SendBlock.ts
> +                    });
다음 블록을 넣기까지 지연시간이 새로운 블록이 생성되는 14초 정도 필요합니다.

2022-12-08 04:35 UTC, TrustHenry commented on src/service/scheduler/SendBlock.ts
> +            ) as RollUp;
적용 되었습니다.

2022-12-08 05:00 UTC, TrustHenry commented on src/service/scheduler/SendBlock.ts
> +            const last_height: BigNumber = await this._rollup.connect(this._adminSigner).getLastHeight();
적용 되었습니다.

2022-12-08 07:45 UTC, TrustHenry commented on src/main.ts
> +            schedulers.push(new SendBlock());
적용 되었습니다.

2022-12-08 07:47 UTC, TrustHenry commented on src/service/scheduler/SendBlock.ts
> +                    });
scheduler.items ("send_block") 에 interval 값을 추가 하였습니다.

2022-12-08 07:54 UTC, Kang-Simon commented on src/main.ts
> +            schedulers.push(new SendBlock(send_block_scheduler.interval));
```suggestion
        let scheduler = config.scheduler.getScheduler("node");
        if (scheduler && scheduler.enable) {
            schedulers.push(new Node(scheduler.interval));
        }
        scheduler = config.scheduler.getScheduler("send_block");
        if (scheduler && scheduler.enable) {
            schedulers.push(new SendBlock(scheduler.interval));
```

2022-12-08 08:23 UTC, Kang-Simon commented on src/service/scheduler/SendBlock.ts
> +    uint64max = 18446744073709551615n;
```suggestion
    private uint64max = 18446744073709551615n;
```

2022-12-08 08:23 UTC, Kang-Simon commented on src/service/scheduler/SendBlock.ts
> +    rollup_artifact = JSON.parse(fs.readFileSync("./artifacts/contracts/RollUp.sol/RollUp.json", "utf8"));
```suggestion
    private rollup_artifact = JSON.parse(fs.readFileSync("./artifacts/contracts/RollUp.sol/RollUp.json", "utf8"));
```

2022-12-09 00:20 UTC, TrustHenry commented on src/service/scheduler/SendBlock.ts
> +    uint64max = 18446744073709551615n;
적용 하였습니다.

2022-12-09 01:48 UTC, MichaelKim20 requested changes
확인해주세요~

2022-12-09 01:48 UTC, MichaelKim20 commented on src/service/scheduler/SendBlock.ts
> +                    });
이것은 좀 복잡한 부분이 있으니 병합후에 몇가지 테스트를 해보는것이 좋겠습니다.

2022-12-09 01:48 UTC, MichaelKim20 commented on src/service/scheduler/SendBlock.ts
> +                BigNumber.from(await this._rollup.connect(this.adminSigner).getLastHeight()).toString()
```suggestion
                (await this._rollup.getLastHeight()).toString()
```
이 함수는 서명을 하지 않아도 되기 때문에 connect를 사용하지 않아도 되네요.
리턴값이 이미 BigNumber이기 때문에 toString()을 사용해서 문자열로 변환하면 됩니다.

2022-12-09 01:48 UTC, MichaelKim20 commented on src/service/scheduler/Node.ts
> +    private _adminSigner: NonceManager | undefined;
_managerSigner 가 좋을 것 같아요

2022-12-09 01:48 UTC, MichaelKim20 commented on src/service/scheduler/SendBlock.ts
> +    private _adminSigner: NonceManager | undefined;
_managerSigner 가 좋겠습니다.

2022-12-09 01:48 UTC, MichaelKim20 commented on src/service/scheduler/Node.ts
> +        );
```suggestion
       const last_height = BigInt((await this._rollup.getLastHeight()).toString());
```

2022-12-09 02:06 UTC, TrustHenry commented on src/service/scheduler/Node.ts
> +    private _adminSigner: NonceManager | undefined;
Node.ts 에서 삭제하고 SendBlock 에 적용 하였습니다.

2022-12-09 02:06 UTC, TrustHenry commented on src/service/scheduler/SendBlock.ts
> +                BigNumber.from(await this._rollup.connect(this.adminSigner).getLastHeight()).toString()
적용 하였습니다.

2022-12-09 02:06 UTC, TrustHenry commented on src/service/scheduler/SendBlock.ts
> +    private _adminSigner: NonceManager | undefined;
적용 하였습니다.

2022-12-09 02:08 UTC, TrustHenry commented on src/service/scheduler/Node.ts
> +        );
Node.ts 에서 DB의 블록높이를 바라보도록 수정 하였습니다.

2022-12-09 02:20 UTC, MichaelKim20 requested changes

2022-12-09 02:20 UTC, MichaelKim20 commented on src/service/scheduler/Node.ts
> +                        if (db_last_height > 0) {
```suggestion
                        if (!Number.isNaN(db_last_height)) {
```

2022-12-09 02:27 UTC, TrustHenry commented on src/service/scheduler/Node.ts
> +                        if (db_last_height > 0) {
DB에는 블록높이가 0 초과 저장 되어 있어야 DB기준으로 블록을 생성 합니다.
제네시스블록은 Node의 초기값 prev_height = -1 에서 시작 합니다.

2022-12-09 02:29 UTC, TrustHenry commented on src/service/scheduler/Node.ts
> +                        if (db_last_height > 0) {
아 이런경우가 있을것 같습니다.
Node의 파일DB가 완전히 삭제 되어버려 다시 실행 할때 스마트컨트랙 Rollup 에서의 마지막 블록높이가 10인경우
Node는 제네시스 블록부터 새로 생성 할 것 같습니다.
이경우 스마트컨트랙 Rollup을 읽어서 높이를 복구 해야 할 것 같습니다.

2022-12-09 02:31 UTC, MichaelKim20 commented on src/service/scheduler/Node.ts
> +                        if (db_last_height > 0) {
레코드가 없을때는 Number.NaN을 리턴하네요
 그리고 제네시스 블록이 DB에 들어 있을 때는 그 높이가 0이 겠지요
그 이후에 1번을 저장할려고 했을 때, 이전블록높이는 0입니다

2022-12-09 02:56 UTC, MichaelKim20 approved these changes
LGTM

2022-12-09 02:56 UTC, merged